.\" This man page is inspired in hello.1 from GNU hello-2.10.
.TH BOMBERMAN "21" "January 2019" "bomberman 2.0" "User Commands"
.SH NAME
bomberman - play the game
.SH SYNOPSIS
.B bomberman server port || bomberman client ip_address port
.SH DESCRIPTION
Play the game, server and client sides.
.SH AUTHORS
Original work by Lars Wirzenius, 2010.
.br
Reverse engineered (with permission) by NADA MESARTI, 2019.
